"""new_attr column added in resource2

Revision ID: eb834f7f70c9
Revises: 2c36803f0976
Create Date: 2025-04-08 19:20:19.384266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb834f7f70c9'
down_revision: Union[str, None] = '2c36803f0976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource2', sa.Column('new_attr', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource2', 'new_attr')
    # ### end Alembic commands ###
