"""new_attr column deleted from resource2

Revision ID: 1368eb70bae4
Revises: eb834f7f70c9
Create Date: 2025-04-08 19:47:28.517650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1368eb70bae4'
down_revision: Union[str, None] = 'eb834f7f70c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource2', 'new_attr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource2', sa.Column('new_attr', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
